version: '3.8'

services:
  # 1. Database Service
  mysqldb:
    image: mysql:8.0
    container_name: fitlife_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitlife_db
    ports:
      - "3307:3306" # Map ra port 3307 để tránh đụng MySQL local
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fitlife-net

  # 2. Redis Service
  redis:
    image: redis:alpine
    container_name: fitlife_redis
    ports:
      - "6380:6379" # Map ra port 6380
    networks:
      - fitlife-net

  # 3. Backend Service (Spring Boot)
  app:
    build: .
    container_name: fitlife_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/fitlife_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysqldb
      - redis
    networks:
      - fitlife-net

volumes:
  db_data:

networks:
  fitlife-net:
    driver: bridge